services:
  psinmr:
    build:
      context: .
      dockerfile: Dockerfile
    image: psinmr:latest
    container_name: psinmr
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
